"""Base model and field types used by every contract."""

from typing import Annotated

from pydantic import BaseModel, ConfigDict, StringConstraints

# Text that must contain something besides whitespace; surrounding whitespace is removed.
NonEmptyStr = Annotated[str, StringConstraints(strip_whitespace=True, min_length=1)]

# Turn ids are generated by the Mac (uuid4 hex) and show up in logs, so keep them simple.
TurnId = Annotated[str, StringConstraints(pattern=r"^[A-Za-z0-9_-]+$", min_length=1, max_length=64)]


class Contract(BaseModel):
    """Base for every shared model: immutable, and unknown fields are rejected."""

    model_config = ConfigDict(frozen=True, extra="forbid")
